### ISSUE TITLE
TYPO CORRECTION

### ISSUE THREAD

**Issue by adrianvele** [adrianvele/velements#2]
fiecare expresie trebuie sa fie pe cate un rand:

Upcycled fashion 
Sustainable fashion
Born again clothes
Reconstructed
Second chance
Fast fashion revolution.

<img width="457" alt="Screen Shot 2021-09-15 at 16 11 31" src="https://user-images.githubusercontent.com/90404277/133439945-446167ce-536b-4268-aa33-336ab4b6d888.png">

**Comment by bensinca** [comment]
This can be done in the admin
